# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box = "bento/opensuse-leap-42.1"

 config.vm.provider "virtualbox" do |vb|
    vb.name = "OpenSuse Leap"

  
    vb.memory = "4096"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--vram", "96"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
    vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'ac97']

    config.vm.network "forwarded_port", guest: 9080, host: 9080
    config.vm.network "forwarded_port", guest: 9081, host: 9081
    config.vm.network "forwarded_port", guest: 9082, host: 9082
    config.vm.network "forwarded_port", guest: 9083, host: 9083
 end

 config.vm.provision "shell", inline: <<-SHELL
    sudo zypper --non-interactive addrepo http://download.opensuse.org/repositories/openSUSE:Leap:42.1:Update/standard/openSUSE:Leap:42.1:Update.repo
    sudo zypper --non-interactive refresh
    sudo zypper --non-interactive install docker
    sudo zypper --non-interactive install vim

    sudo gpasswd -a vagrant docker
    sudo usermod -aG docker vagrant

    sudo systemctl start docker.service
    sudo systemctl enable docker.service
    sudo chkconfig docker on

    sudo localectl set-keymap de

    sudo reboot
SHELL
end